### ISSUE TITLE
训练时错误

### ISSUE THREAD

**Issue by KA1K1** [yz-wang/TogetherNet#4]
已

**Comment by KA1K1** [comment]
Traceback (most recent call last):
  File "TogetherNet-main\train.py", line 165, in <module>
    fit_one_epoch(model_train, model, yolo_loss, loss_history, optimizer, epoch, epoch_step, epoch_step_val, gen, gen_val, UnFreeze_Epoch, Cuda, save_period)
  File "TogetherNet-main\utils\utils_fit.py", line 35, in fit_one_epoch
    outputs = model_train(hazy_and_clear)
  File "AnaVirenvs\Tog02\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "AnaVirenvs\Tog02\lib\site-packages\torch\nn\parallel\data_parallel.py", line 166, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "AnaVirenvs\Tog02\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "TogetherNet-main\nets\yolo.py", line 309, in forward
    fpn_outs    = self.backbone.forward(x)
  File "TogetherNet-main\nets\yolo.py", line 226, in forward
    input, clear_x = input.split((4, 4), dim=0)  # split haze and clear images (Batchsize, Batchsize)
  File "AnaVirenvs\Tog02\lib\site-packages\torch\_tensor.py", line 611, in split
    return super(Tensor, self).split_with_sizes(split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 16 (input tensor's size at dimension 0), but got split_sizes=[4, 4]

进程已结束,退出代码1

**Comment by KA1K1** [comment]
已解决：在yolo.py第226行修改
